### ISSUE TITLE
Add way to configure verbosity

### ISSUE THREAD

**Issue by shanear** [senny/pdfjs_viewer-rails#10]
We're running some automated tests via PhantomJS using the PDF viewer, and it'd be nice to be able to turn off the `"Warning: Setting up fake worker."` output on every test run.

PDFJS allows you to configure it's verbosity, but it's difficult to configure it via the `.pdfjs_viewer` helper method. I'm thinking the best way to do that might be to add a `verbosity:` option.

Thoughts?

**Comment by senny** [comment]
@shanear sorry for the extremely long delay. This seems like a reasonable addition, do you want to give it a go?
