### ISSUE TITLE
uninitialized constant PdfjsViewer (NameError)

### ISSUE THREAD

**Issue by roomaroom** [senny/pdfjs_viewer-rails#21]
In production mode I got this error
`config/routes.rb:17:in  block in <top (required)> : uninitialized constant PdfjsViewer (NameError)`
My routes.rb 
`mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'`
In development mode everything is ok

**Comment by Elektron1c97** [comment]
I'm pretty sure that your whole production environment is broken. Can you load any other dependency?

**Comment by buncismamen** [comment]
I have this issue before, what I'm doing to fix this is, remove `mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'`from routes.rb and gem 'pdfjs_viewer-rails' from Gemfile
then bundle
after that 
I put the `gem 'pdfjs_viewer-rails' ` to the Gemfile and bundle install
then make sure the pdfjs_viewer-rails is loaded 
then I put this `mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'` to my routes.rb 
now its work

**Comment by siegy22** [comment]
@roomaroom are you using Spring? Maybe spring cached a corrupt state. 😐

**Comment by evolve2k** [comment]
I've just run the project now on Rails 7 and it's working as expected. 
This issue is 5 years old, Im guessing it is no longer relevant.

Recommend close.

**Comment by senny** [comment]
@evolve2k Thanks for your feedback. I'm closing the issue. If the problem comes up again, we can reopen.
