### ISSUE TITLE
get all pdfinfo / document properties

### ISSUE THREAD

**Issue by dimitrideruiter** [senny/pdfjs_viewer-rails#23]
Is it possible to get pdf properties using this gem? If so how?

**Comment by senny** [comment]
This gem just packages the PDF.js library and adds some helpers to integrate it with Rails. Everything is client-side. You can check out the PDF.js docs for details about the library.

**Comment by Elektron1c97** [comment]
You can find the docs [here](http://mozilla.github.io/pdf.js/)
