### ISSUE TITLE
couldn't find file 'pdfjs_viewer/pdfjs/compatibility'

### ISSUE THREAD

**Issue by basmoura** [senny/pdfjs_viewer-rails#25]
Hi, I've tried to remove the pdfjs_viewer-rails gem from my project but i'm facing the follow error
```
couldn't find file 'pdfjs_viewer/pdfjs/compatibility' with type 'application/javascript'
```

I already removed the gem from gem file, run the `bundle`command and remove the mounter from routes.rb but nothing changed

**Comment by eliasdevelop** [comment]
Same here!

**Comment by basmoura** [comment]
forget about it
