### ISSUE TITLE
Integrate with iframe

### ISSUE THREAD

**Issue by topnessman** [senny/pdfjs_viewer-rails#31]
Can you please give a full example of the syntax to integrate with irame? 
`<%=pdfjs_viewer pdf_url: "/sample.pdf", style: :full %>` is too simple for me.

**Comment by jmarceli** [comment]
Hi, I'm not sure if it is what are you looking for, but you may try to use the following code on your page:
```
<iframe src="<%= pdfjs.full_path(file: "/here/is/you/pdf/url.pdf") %>" style="width: 100%; height: 100%">
</iframe>
```

**Comment by evolve2k** [comment]
I reckon that resolved it.

Recommend Close.
