### ISSUE TITLE
Sass deprecated soon

### ISSUE THREAD

**Issue by xinlangzi** [senny/pdfjs_viewer-rails#50]
This gem has dependency sass_rails which use sass too. Ruby Sass is deprecated and will be unmaintained as of 26 March 2019. Will you update dependency to use sassc_rails? Thank you.

[http://sass.logdown.com/posts/7081811 ](http://sass.logdown.com/posts/7081811)

**Comment by xinlangzi** [comment]
@senny @jone 

Do you have any plan to upgrade to sassc_rails?

**Comment by jone** [comment]
@xinlangzi thanks for pointing out.
@siegy22 will take care of it. He us offline until next year though.

**Comment by aguynamedben** [comment]
Any update on this? I'm upgrading to Rails 6. Rails 6 which moves off sass-rails by specifying this version of it:
```
gem "sass-rails", ">= 6"
```
That version of sass-rails is really just a wrapper for sassc-rails ([link](https://github.com/rails/sass-rails/releases)).

**Comment by simonc** [comment]
Hi! Same issue here, upgrading to Rails 6 and I got stuck when updating `sass-rails`.

**Comment by matt-doeringtech** [comment]
Hi all.  Love to get this fixed.  Sort of stuck otherwise

**Comment by senny** [comment]
Hi!
I've put up a patch to make this transition happen (#67). I'm not using this gem anymore, so any assistance to help test would be very much welcome. It would be great if someone could run their project with based on the branch in the PR and report back if everything behaves as it should.
