### ISSUE TITLE
Syntax Error in Helper

### ISSUE THREAD

**Issue by Patrax** [senny/pdfjs_viewer-rails#7]
When deploying to Heroku, this error comes up.

Important part:

    def pdfjs_viewer(style:, pdf_url: nil, title: nil)

Full error:

    /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require': /app/vendor/bundle/ruby/2.0.0/gems/pdfjs_viewer-rails-0.0.6/lib/pdfjs_viewer-rails/helpers.rb:4: syntax error, unexpected ',' (SyntaxError)
    2015-11-17T19:29:45.025205+00:00 app[web.1]:       def pdfjs_viewer(style:, pdf_url: nil, title: nil)

**Comment by rambino** [comment]
remove the : at the end of style. 

    def pdfjs_viewer(style, pdf_url: nil, title: nil)

**Comment by almacha** [comment]
I had the same problem. The issue is that in my case I cannot easily modify the file provided by the gem since I have an automatic deployment in AWS: machine starts, git pull, bundle install, then rails runner something and it crashes because of this bug.

**Comment by senny** [comment]
@Patrax this library requires at least Ruby 2.1
