### ISSUE TITLE
undefined method `cover_image' for nil:NilClass

### ISSUE THREAD

**Issue by sunny2601** [senny/pdfjs_viewer-rails#9]
i am getting this issue "undefined method `cover_image' for nil:NilClass"

**Comment by senny** [comment]
Hey @sunny2601 this is not enough information to assist you. Please provide the full backtrace and the code that's causing the issue. Even better would be a small sample application on GitHub that illustrates the issue.

I'm going to close the issue for now, if you still experience the issue, please report back with additional data and I'm going to reopen.
